# Site settings
title: E-commerce Website
description: A virtual market place that allows users buy and sell goods and digital products with ease.
baseurl: "/danielofodile.github.io" # the subpath of your site, e.g. /blog
url: "https://danielofodile.github.io/ecommercewebsite.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Navigation links
nav:
  - Home: /index.html
  - About: /about.html
  - Blog: /blog/index.html
  - Contact: /contact.html

plugins:
  - jekyll-collections

